### ISSUE TITLE
hparams.hparams' has no attribute 'preemphasis

### ISSUE THREAD

**Issue by wanyang6-tal** [polvanrijn/VoiceMe#7]
I tried all versions of "hparams" and I still get this issue: AttributeError: module 'hparams.hparams' has no attribute 'preemphasis'
python=3.9
linux

**Comment by wanyang6-tal** [comment]
[ERROR] Exception on /api/tts_lipsync/synthesize_batched [POST]
Traceback (most recent call last):
  File "/home/user/mnt/conda/envs/voiceme/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/mnt/conda/envs/voiceme/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/mnt/conda/envs/voiceme/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/mnt/conda/envs/voiceme/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/user/mnt2/tasks/VoiceMe/server.py", line 425, in generate
    synthesize(tmp_wav_path, reference_filename, tmp_video_path)
  File "/home/user/mnt2/tasks/VoiceMe/server.py", line 278, in synthesize
    mel = audio.melspectrogram(wav)
  File "/home/user/mnt2/tasks/VoiceMe/Wav2Lip/audio.py", line 46, in melspectrogram
    D = _stft(preemphasis(wav, hp.preemphasis, hp.preemphasize))
AttributeError: module 'hparams.hparams' has no attribute 'preemphasis'

**Comment by wanyang6-tal** [comment]
> I tried all versions of "hparams" and I still get this issue: AttributeError: module 'hparams.hparams' has no attribute 'preemphasis' python=3.9 linux

**Comment by wcong5252** [comment]
Have you solved it yet

**Comment by polvanrijn** [comment]
This is a problem with Wav2Lib. Please ask them for support if needed.
